package com.azizjonkasimov.lifesimulator.domain.engine

import com.azizjonkasimov.lifesimulator.domain.model.ActionEffect
import com.azizjonkasimov.lifesimulator.domain.model.ActionCategory
import com.azizjonkasimov.lifesimulator.domain.model.DailyActionDefinition

object ActionCatalog {
    val actions: List<DailyActionDefinition> = listOf(
        DailyActionDefinition(
            id = "work_shift",
            title = "Work Shift",
            description = "Put in focused hours at your main job.",
            category = ActionCategory.WORK,
            timeCost = 5,
            energyCost = 28,
            effect = ActionEffect(
                cashDelta = 0,
                moodDelta = -3,
                stressDelta = 10,
                careerXpDelta = 12,
                reputationDelta = 3,
                promotionReadinessDelta = 8,
                goalProgress = mapOf("first_promotion" to 8),
            ),
            tags = listOf("income", "career"),
        ),
        DailyActionDefinition(
            id = "overtime",
            title = "Overtime",
            description = "Trade a rough evening for extra money and visibility.",
            category = ActionCategory.WORK,
            timeCost = 3,
            energyCost = 24,
            effect = ActionEffect(
                cashDelta = 85,
                healthDelta = -2,
                moodDelta = -5,
                stressDelta = 14,
                careerXpDelta = 8,
                reputationDelta = 4,
                promotionReadinessDelta = 7,
            ),
            tags = listOf("income", "stress"),
        ),
        DailyActionDefinition(
            id = "study_course",
            title = "Study Course",
            description = "Work through a practical course that improves future options.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 20,
            moneyCost = 30,
            effect = ActionEffect(
                moodDelta = -1,
                stressDelta = 4,
                knowledgeDelta = 18,
                careerXpDelta = 7,
                creativityDelta = 3,
                promotionReadinessDelta = 8,
                goalProgress = mapOf("first_promotion" to 8),
            ),
            tags = listOf("skill", "course"),
        ),
        DailyActionDefinition(
            id = "apply_jobs",
            title = "Apply for Jobs",
            description = "Refine applications, send them out, and build optionality.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 16,
            effect = ActionEffect(
                moodDelta = -2,
                stressDelta = 6,
                careerXpDelta = 8,
                communicationDelta = 5,
                networkDelta = 3,
                promotionReadinessDelta = 18,
                goalProgress = mapOf("first_promotion" to 12),
            ),
            tags = listOf("career", "opportunity"),
        ),
        DailyActionDefinition(
            id = "freelance_gig",
            title = "Freelance Gig",
            description = "Take a flexible contract for cash, reputation, and practice.",
            category = ActionCategory.WORK,
            timeCost = 4,
            energyCost = 30,
            effect = ActionEffect(
                cashDelta = 0,
                moodDelta = -4,
                stressDelta = 13,
                careerXpDelta = 9,
                knowledgeDelta = 3,
                creativityDelta = 7,
                reputationDelta = 5,
            ),
            tags = listOf("income", "portfolio"),
        ),
        DailyActionDefinition(
            id = "budget_review",
            title = "Budget Review",
            description = "Review bills, move money deliberately, and reduce financial anxiety.",
            category = ActionCategory.MONEY,
            timeCost = 1,
            energyCost = 8,
            effect = ActionEffect(
                cashDelta = 10,
                debtDelta = -20,
                creditScoreDelta = 3,
                moodDelta = 2,
                stressDelta = -7,
                goalProgress = mapOf("emergency_buffer" to 20),
            ),
            tags = listOf("finance", "planning"),
        ),
        DailyActionDefinition(
            id = "exercise",
            title = "Exercise",
            description = "Train your body and release pressure.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 18,
            effect = ActionEffect(
                healthDelta = 7,
                moodDelta = 5,
                stressDelta = -9,
                fitnessDelta = 12,
                goalProgress = mapOf("stable_week" to 1),
            ),
            tags = listOf("health", "stress"),
        ),
        DailyActionDefinition(
            id = "rest",
            title = "Rest",
            description = "Take deliberate recovery time.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 0,
            effect = ActionEffect(
                healthDelta = 2,
                moodDelta = 4,
                energyDelta = 24,
                stressDelta = -13,
                goalProgress = mapOf("stable_week" to 1),
            ),
            tags = listOf("recovery"),
        ),
        DailyActionDefinition(
            id = "cook_at_home",
            title = "Cook at Home",
            description = "Spend a quiet evening on a cheap, healthy meal.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 10,
            moneyCost = 8,
            effect = ActionEffect(
                healthDelta = 5,
                moodDelta = 2,
                stressDelta = -4,
                goalProgress = mapOf("stable_week" to 1, "emergency_buffer" to 10),
            ),
            tags = listOf("health", "low cost"),
        ),
        DailyActionDefinition(
            id = "socialize",
            title = "Socialize",
            description = "Spend time with people who keep life human.",
            category = ActionCategory.SOCIAL,
            timeCost = 3,
            energyCost = 16,
            moneyCost = 18,
            effect = ActionEffect(
                moodDelta = 9,
                stressDelta = -6,
                socialDelta = 13,
                friendsDelta = 12,
                communicationDelta = 4,
                goalProgress = mapOf("social_circle" to 12),
            ),
            tags = listOf("friends", "mood"),
        ),
        DailyActionDefinition(
            id = "call_family",
            title = "Call Family",
            description = "Check in with family and restore a little emotional baseline.",
            category = ActionCategory.SOCIAL,
            timeCost = 1,
            energyCost = 6,
            effect = ActionEffect(
                moodDelta = 4,
                stressDelta = -3,
                socialDelta = 5,
                familyDelta = 10,
                goalProgress = mapOf("social_circle" to 8),
            ),
            tags = listOf("family", "quick"),
        ),
        DailyActionDefinition(
            id = "networking",
            title = "Networking",
            description = "Meet peers and weak ties who can open future doors.",
            category = ActionCategory.SOCIAL,
            timeCost = 2,
            energyCost = 14,
            moneyCost = 10,
            effect = ActionEffect(
                moodDelta = 2,
                stressDelta = 2,
                socialDelta = 7,
                networkDelta = 12,
                communicationDelta = 8,
                reputationDelta = 7,
                careerXpDelta = 6,
                promotionReadinessDelta = 6,
                goalProgress = mapOf("social_circle" to 10, "first_promotion" to 6),
            ),
            tags = listOf("network", "career"),
        ),
    )
}
