package com.azizjonkasimov.lifesimulator.domain.engine

import com.azizjonkasimov.lifesimulator.domain.model.ActionCategory
import com.azizjonkasimov.lifesimulator.domain.model.ActionEffect
import com.azizjonkasimov.lifesimulator.domain.model.DailyActionDefinition

object ActionCatalog {
    val actions: List<DailyActionDefinition> = listOf(
        DailyActionDefinition(
            id = "temp_shift",
            title = "Temp Shift",
            description = "Take short-term work for immediate cash while you search for something steadier.",
            category = ActionCategory.WORK,
            timeCost = 4,
            energyCost = 24,
            effect = ActionEffect(
                cashDelta = 65,
                moodDelta = -2,
                stressDelta = 9,
                careerXpDelta = 3,
            ),
            tags = listOf("income", "fallback"),
        ),
        DailyActionDefinition(
            id = "send_applications",
            title = "Send Applications",
            description = "Tighten your resume, send targeted applications, and build employer interest.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 16,
            effect = ActionEffect(
                moodDelta = -1,
                stressDelta = 5,
                careerXpDelta = 4,
                communicationDelta = 3,
                applicationsDelta = 2,
                offerProgressDelta = 16,
            ),
            tags = listOf("job search", "career"),
        ),
        DailyActionDefinition(
            id = "interview_prep",
            title = "Interview Prep",
            description = "Practice answers and sharpen examples so interviews convert into offers.",
            category = ActionCategory.GROWTH,
            timeCost = 2,
            energyCost = 14,
            effect = ActionEffect(
                stressDelta = 3,
                knowledgeDelta = 6,
                communicationDelta = 5,
                interviewReadinessDelta = 18,
                offerProgressDelta = 8,
            ),
            tags = listOf("job search", "readiness"),
        ),
        DailyActionDefinition(
            id = "attend_interview",
            title = "Attend Interview",
            description = "Use your applications and preparation to turn a job lead into a real offer.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 24,
            effect = ActionEffect(
                moodDelta = -2,
                stressDelta = 8,
                communicationDelta = 4,
                reputationDelta = 2,
            ),
            tags = listOf("job search", "offer"),
        ),
        DailyActionDefinition(
            id = "work_shift",
            title = "Work Shift",
            description = "Put in focused hours at your main job.",
            category = ActionCategory.WORK,
            timeCost = 5,
            energyCost = 28,
            effect = ActionEffect(
                moodDelta = -3,
                stressDelta = 9,
                careerXpDelta = 12,
                reputationDelta = 3,
                promotionReadinessDelta = 8,
            ),
            tags = listOf("income", "career"),
        ),
        DailyActionDefinition(
            id = "overtime",
            title = "Overtime",
            description = "Trade a rough evening for extra money and visibility.",
            category = ActionCategory.WORK,
            timeCost = 3,
            energyCost = 24,
            effect = ActionEffect(
                healthDelta = -2,
                moodDelta = -5,
                stressDelta = 14,
                careerXpDelta = 8,
                reputationDelta = 4,
                promotionReadinessDelta = 7,
            ),
            tags = listOf("income", "stress"),
        ),
        DailyActionDefinition(
            id = "manager_check_in",
            title = "Manager Check-in",
            description = "Clarify expectations and convert steady work into visible progress.",
            category = ActionCategory.WORK,
            timeCost = 2,
            energyCost = 14,
            effect = ActionEffect(
                moodDelta = 1,
                stressDelta = 4,
                careerXpDelta = 7,
                communicationDelta = 5,
                reputationDelta = 9,
                promotionReadinessDelta = 12,
            ),
            tags = listOf("career", "visibility"),
        ),
        DailyActionDefinition(
            id = "study_course",
            title = "Study Course",
            description = "Work through a practical course that improves future options.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 20,
            moneyCost = 30,
            effect = ActionEffect(
                moodDelta = -1,
                stressDelta = 4,
                knowledgeDelta = 18,
                careerXpDelta = 7,
                creativityDelta = 3,
                promotionReadinessDelta = 8,
            ),
            tags = listOf("skill", "course"),
        ),
        DailyActionDefinition(
            id = "networking",
            title = "Networking",
            description = "Meet peers and weak ties who can open future doors.",
            category = ActionCategory.SOCIAL,
            timeCost = 2,
            energyCost = 14,
            moneyCost = 10,
            effect = ActionEffect(
                moodDelta = 2,
                stressDelta = 2,
                socialDelta = 7,
                networkDelta = 12,
                communicationDelta = 8,
                reputationDelta = 7,
                careerXpDelta = 6,
                promotionReadinessDelta = 6,
            ),
            tags = listOf("network", "career"),
        ),
        DailyActionDefinition(
            id = "research_offer",
            title = "Research Offer",
            description = "Choose a client problem and shape a service people might actually buy.",
            category = ActionCategory.BUSINESS,
            timeCost = 2,
            energyCost = 14,
            effect = ActionEffect(
                stressDelta = 3,
                creativityDelta = 8,
                businessReputationDelta = 3,
                pipelineValueDelta = 15,
            ),
            tags = listOf("business", "offer"),
        ),
        DailyActionDefinition(
            id = "find_leads",
            title = "Find Leads",
            description = "Look for people or small teams with a problem your service can solve.",
            category = ActionCategory.BUSINESS,
            timeCost = 2,
            energyCost = 16,
            effect = ActionEffect(
                stressDelta = 4,
                communicationDelta = 4,
                leadsDelta = 2,
                pipelineValueDelta = 8,
            ),
            tags = listOf("business", "pipeline"),
        ),
        DailyActionDefinition(
            id = "pitch_client",
            title = "Pitch Client",
            description = "Turn a lead into a paid project with a specific, useful pitch.",
            category = ActionCategory.BUSINESS,
            timeCost = 3,
            energyCost = 20,
            effect = ActionEffect(
                stressDelta = 6,
                communicationDelta = 5,
                creativityDelta = 5,
                leadsDelta = -1,
                activeProjectsDelta = 1,
                clientTrustDelta = 5,
                businessReputationDelta = 3,
            ),
            tags = listOf("business", "client"),
        ),
        DailyActionDefinition(
            id = "client_project",
            title = "Client Project",
            description = "Complete paid client work and turn the pipeline into cash and trust.",
            category = ActionCategory.BUSINESS,
            timeCost = 4,
            energyCost = 30,
            effect = ActionEffect(
                moodDelta = -2,
                stressDelta = 12,
                creativityDelta = 5,
                activeProjectsDelta = -1,
                completedProjectsDelta = 1,
                clientTrustDelta = 8,
                businessReputationDelta = 8,
                pipelineValueDelta = 8,
            ),
            tags = listOf("income", "business"),
        ),
        DailyActionDefinition(
            id = "improve_offer",
            title = "Improve Offer",
            description = "Polish your service package so pitches are easier to understand and close.",
            category = ActionCategory.BUSINESS,
            timeCost = 2,
            energyCost = 16,
            moneyCost = 25,
            effect = ActionEffect(
                stressDelta = 3,
                creativityDelta = 10,
                businessReputationDelta = 2,
                pipelineValueDelta = 20,
            ),
            tags = listOf("business", "quality"),
        ),
        DailyActionDefinition(
            id = "invest_tools",
            title = "Invest in Tools",
            description = "Buy simple tools that make your client work faster and more credible.",
            category = ActionCategory.BUSINESS,
            timeCost = 1,
            energyCost = 6,
            moneyCost = 80,
            effect = ActionEffect(
                stressDelta = 4,
                clientTrustDelta = 6,
                businessReputationDelta = 5,
                pipelineValueDelta = 35,
            ),
            tags = listOf("business", "investment"),
        ),
        DailyActionDefinition(
            id = "budget_review",
            title = "Budget Review",
            description = "Review bills, move money deliberately, and reduce financial anxiety.",
            category = ActionCategory.MONEY,
            timeCost = 1,
            energyCost = 8,
            effect = ActionEffect(
                cashDelta = 10,
                debtDelta = -20,
                creditScoreDelta = 3,
                moodDelta = 2,
                stressDelta = -7,
            ),
            tags = listOf("finance", "planning"),
        ),
        DailyActionDefinition(
            id = "exercise",
            title = "Exercise",
            description = "Train your body and release pressure.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 18,
            effect = ActionEffect(
                healthDelta = 7,
                moodDelta = 5,
                stressDelta = -9,
                fitnessDelta = 12,
            ),
            tags = listOf("health", "stress"),
        ),
        DailyActionDefinition(
            id = "rest",
            title = "Rest",
            description = "Take deliberate recovery time.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 0,
            effect = ActionEffect(
                healthDelta = 2,
                moodDelta = 4,
                energyDelta = 24,
                stressDelta = -13,
            ),
            tags = listOf("recovery"),
        ),
        DailyActionDefinition(
            id = "cook_at_home",
            title = "Cook at Home",
            description = "Spend a quiet evening on a cheap, healthy meal.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 10,
            moneyCost = 8,
            effect = ActionEffect(
                healthDelta = 5,
                moodDelta = 2,
                stressDelta = -4,
            ),
            tags = listOf("health", "low cost"),
        ),
        DailyActionDefinition(
            id = "socialize",
            title = "Socialize",
            description = "Spend time with people who keep life human.",
            category = ActionCategory.SOCIAL,
            timeCost = 3,
            energyCost = 16,
            moneyCost = 18,
            effect = ActionEffect(
                moodDelta = 9,
                stressDelta = -6,
                socialDelta = 13,
                friendsDelta = 12,
                communicationDelta = 4,
            ),
            tags = listOf("friends", "mood"),
        ),
        DailyActionDefinition(
            id = "call_family",
            title = "Call Family",
            description = "Check in with family and restore a little emotional baseline.",
            category = ActionCategory.SOCIAL,
            timeCost = 1,
            energyCost = 6,
            effect = ActionEffect(
                moodDelta = 4,
                stressDelta = -3,
                socialDelta = 5,
                familyDelta = 10,
            ),
            tags = listOf("family", "quick"),
        ),
    )
}
