package com.azizjonkasimov.lifesimulator.domain.engine

import com.azizjonkasimov.lifesimulator.domain.model.ActionCategory
import com.azizjonkasimov.lifesimulator.domain.model.ActionEffect
import com.azizjonkasimov.lifesimulator.domain.model.DailyActionDefinition

/**
 * The things you can do with a day. Cash from gigs, shifts, overtime, interviews,
 * and client work is computed dynamically in the engine; the static effects below
 * are the predictable stat changes. Income, debt, savings, and investing live on
 * the Money tab, not here.
 */
object ActionCatalog {
    val actions: List<DailyActionDefinition> = listOf(
        // --- Quick money ---
        DailyActionDefinition(
            id = "gig_work",
            title = "Gig Work",
            description = "Pick up short-term work for fast cash. A car makes it pay more.",
            category = ActionCategory.WORK,
            timeCost = 4,
            energyCost = 22,
            effect = ActionEffect(moodDelta = -2, stressDelta = 8, careerSkillDelta = 2),
            tags = listOf("income"),
        ),
        DailyActionDefinition(
            id = "work_shift",
            title = "Work Shift",
            description = "Put in focused hours at your job. Pays your shift rate.",
            category = ActionCategory.WORK,
            timeCost = 5,
            energyCost = 28,
            effect = ActionEffect(
                moodDelta = -3,
                stressDelta = 9,
                careerSkillDelta = 4,
                reputationDelta = 3,
                promotionReadinessDelta = 8,
            ),
            tags = listOf("income", "career"),
        ),
        DailyActionDefinition(
            id = "overtime",
            title = "Overtime",
            description = "Trade a rough evening for extra pay and visibility.",
            category = ActionCategory.WORK,
            timeCost = 3,
            energyCost = 24,
            effect = ActionEffect(
                healthDelta = -2,
                moodDelta = -4,
                stressDelta = 13,
                careerSkillDelta = 3,
                reputationDelta = 3,
                promotionReadinessDelta = 6,
            ),
            tags = listOf("income", "stress"),
        ),
        // --- Getting hired ---
        DailyActionDefinition(
            id = "apply_jobs",
            title = "Apply to Jobs",
            description = "Send targeted applications and build employer interest.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 16,
            effect = ActionEffect(
                moodDelta = -1,
                stressDelta = 4,
                communicationDelta = 2,
                searchProgressDelta = 16,
            ),
            tags = listOf("job search"),
        ),
        DailyActionDefinition(
            id = "interview_prep",
            title = "Interview Prep",
            description = "Sharpen your answers so interviews actually convert.",
            category = ActionCategory.GROWTH,
            timeCost = 2,
            energyCost = 14,
            effect = ActionEffect(
                stressDelta = 3,
                knowledgeDelta = 4,
                communicationDelta = 5,
                searchProgressDelta = 10,
            ),
            tags = listOf("job search", "readiness"),
        ),
        DailyActionDefinition(
            id = "attend_interview",
            title = "Attend Interview",
            description = "Roll the dice on a real offer. Your prep sets the odds.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 22,
            effect = ActionEffect(stressDelta = 6, communicationDelta = 3),
            tags = listOf("job search", "risk"),
        ),
        // --- Growth ---
        DailyActionDefinition(
            id = "study",
            title = "Take a Course",
            description = "Work through a practical course. A laptop speeds it up.",
            category = ActionCategory.GROWTH,
            timeCost = 3,
            energyCost = 20,
            moneyCost = 30,
            effect = ActionEffect(
                moodDelta = -1,
                stressDelta = 4,
                knowledgeDelta = 16,
                careerSkillDelta = 6,
                creativityDelta = 3,
                promotionReadinessDelta = 6,
            ),
            tags = listOf("skill"),
        ),
        DailyActionDefinition(
            id = "manager_check_in",
            title = "Manager Check-in",
            description = "Make your work visible and push toward a promotion.",
            category = ActionCategory.WORK,
            timeCost = 2,
            energyCost = 14,
            effect = ActionEffect(
                moodDelta = 1,
                stressDelta = 4,
                communicationDelta = 4,
                reputationDelta = 9,
                promotionReadinessDelta = 12,
            ),
            tags = listOf("career", "visibility"),
        ),
        // --- Business ---
        DailyActionDefinition(
            id = "launch_business",
            title = "Launch Side Hustle",
            description = "Turn an idea into a real service you can sell.",
            category = ActionCategory.BUSINESS,
            timeCost = 3,
            energyCost = 18,
            moneyCost = 80,
            effect = ActionEffect(stressDelta = 4, creativityDelta = 6, businessReputationDelta = 5),
            tags = listOf("business"),
        ),
        DailyActionDefinition(
            id = "find_client",
            title = "Find a Client",
            description = "Hunt for paying clients. Reputation improves your chances.",
            category = ActionCategory.BUSINESS,
            timeCost = 3,
            energyCost = 18,
            effect = ActionEffect(stressDelta = 5, communicationDelta = 4, businessReputationDelta = 2),
            tags = listOf("business", "risk"),
        ),
        DailyActionDefinition(
            id = "marketing",
            title = "Marketing Push",
            description = "Raise your reputation so each client pays more.",
            category = ActionCategory.BUSINESS,
            timeCost = 2,
            energyCost = 14,
            moneyCost = 40,
            effect = ActionEffect(stressDelta = 3, creativityDelta = 5, businessReputationDelta = 12),
            tags = listOf("business", "quality"),
        ),
        DailyActionDefinition(
            id = "upgrade_business",
            title = "Upgrade Business",
            description = "Reinvest to reach the next tier: more clients, higher rates.",
            category = ActionCategory.BUSINESS,
            timeCost = 2,
            energyCost = 16,
            effect = ActionEffect(stressDelta = 6, creativityDelta = 4, businessReputationDelta = 4),
            tags = listOf("business", "investment"),
        ),
        // --- Wellbeing ---
        DailyActionDefinition(
            id = "exercise",
            title = "Exercise",
            description = "Train your body and burn off pressure.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 18,
            effect = ActionEffect(healthDelta = 7, moodDelta = 5, stressDelta = -9, fitnessDelta = 12),
            tags = listOf("health"),
        ),
        DailyActionDefinition(
            id = "rest",
            title = "Rest",
            description = "Deliberate recovery. Clears burnout and refills energy.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 0,
            effect = ActionEffect(healthDelta = 2, moodDelta = 4, energyDelta = 24, stressDelta = -13),
            tags = listOf("recovery"),
        ),
        DailyActionDefinition(
            id = "cook_at_home",
            title = "Cook at Home",
            description = "A cheap, healthy meal and a quiet evening.",
            category = ActionCategory.WELLBEING,
            timeCost = 2,
            energyCost = 10,
            moneyCost = 8,
            effect = ActionEffect(healthDelta = 5, moodDelta = 2, stressDelta = -4),
            tags = listOf("health", "low cost"),
        ),
        // --- People ---
        DailyActionDefinition(
            id = "socialize",
            title = "Socialize",
            description = "Spend time with people who keep life human.",
            category = ActionCategory.SOCIAL,
            timeCost = 3,
            energyCost = 16,
            moneyCost = 18,
            effect = ActionEffect(
                moodDelta = 9,
                stressDelta = -6,
                socialDelta = 13,
                friendsDelta = 12,
                communicationDelta = 4,
            ),
            tags = listOf("friends", "mood"),
        ),
        DailyActionDefinition(
            id = "call_family",
            title = "Call Family",
            description = "Check in with family and restore some baseline.",
            category = ActionCategory.SOCIAL,
            timeCost = 1,
            energyCost = 6,
            effect = ActionEffect(moodDelta = 4, stressDelta = -3, socialDelta = 5, familyDelta = 10),
            tags = listOf("family", "quick"),
        ),
        DailyActionDefinition(
            id = "network",
            title = "Networking",
            description = "Meet peers and weak ties who open future doors.",
            category = ActionCategory.SOCIAL,
            timeCost = 2,
            energyCost = 14,
            moneyCost = 10,
            effect = ActionEffect(
                moodDelta = 2,
                stressDelta = 2,
                socialDelta = 7,
                networkDelta = 12,
                communicationDelta = 8,
                reputationDelta = 7,
                careerSkillDelta = 4,
                promotionReadinessDelta = 4,
                searchProgressDelta = 6,
            ),
            tags = listOf("network", "career"),
        ),
    )
}
